window.isSearchBot=!1;if(/Bot/i.test(navigator.userAgent)){window.isSearchBot=!0}
window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
window.isiOS=!1;if(/iPhone|iPad|iPod/i.test(navigator.userAgent)){window.isiOS=!0}
window.isiOSVersion='';if(window.isiOS){var version=(navigator.appVersion).match(/OS (\d+)_(\d+)_?(\d+)?/);if(version!==null){window.isiOSVersion=[parseInt(version[1],10),parseInt(version[2],10),parseInt(version[3]||0,10)]}}
window.isSafari=!1;if(/^((?!chrome|android).)*safari/i.test(navigator.userAgent)){window.isSafari=!0}
window.isSafariVersion='';if(window.isSafari){var version=(navigator.appVersion).match(/Version\/(\d+)\.(\d+)\.?(\d+)? Safari/);if(version!==null){window.isSafariVersion=[parseInt(version[1],10),parseInt(version[2],10),parseInt(version[3]||0,10)]}}
window.isIE=!!document.documentMode;function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t808_geoRedirect(geo,data){if(!geo||!data)return;if(!window.isSearchBot){var city=geo.city.name_en;var region=geo.region.name_en;var country=geo.country.iso;Array.prototype.forEach.call(data,function(value){if(value.geo.indexOf(country)!==-1||value.geo.indexOf(region)!==-1||value.geo.indexOf(city)!==-1){window.location.href=value.link+window.location.search}})}}
function t446_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var linkItems=rec.querySelectorAll('.t-menu__link-item');var subMenuLinks=rec.querySelectorAll('.t-menusub__link-item');var menu=rec.querySelector('.t446');Array.prototype.forEach.call(linkItems,function(link){link.addEventListener('click',function(){if(link.classList.contains('t-menusub__target-link')||link.classList.contains('tooltipstered')||link.classList.contains('t794__tm-link')||link.classList.contains('t966__tm-link')||link.classList.contains('t978__tm-link'))
return;t446_hideMenuOnMobile(link,rec)})});Array.prototype.forEach.call(subMenuLinks,function(subMenuLink){subMenuLink.addEventListener('click',function(){t446_hideMenuOnMobile(subMenuLink,rec)})})}
function t446_setLogoPadding(recid){var rec=document.getElementById('rec'+recid);if(!rec||window.innerWidth<=980)return;var menu=rec.querySelector('.t446');var logo=menu?menu.querySelector('.t446__logowrapper'):null;var logoWidth=logo?logo.offsetWidth:0;var leftWrapper=menu?menu.querySelector('.t446__leftwrapper'):null;var rightWrapper=menu?menu.querySelector('.t446__rightwrapper'):null;if(leftWrapper)leftWrapper.style.paddingRight=logoWidth/2+50+'px';if(rightWrapper)rightWrapper.style.paddingLeft=logoWidth/2+50+'px'}
function t446_checkOverflow(recid,menuheight){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t446'):null;if(!menu)return;var rightWrapper=menu.querySelector('.t446__rightwrapper');var rightMenuWrap=rightWrapper?rightWrapper.querySelector('.t446__rightmenuwrapper'):null;var additionalWrap=rightWrapper?rightWrapper.querySelector('.t446__additionalwrapper'):null;var burgerWrapOverflow=rightWrapper?rightWrapper.querySelector('.t446__burgerwrapper_overflow'):null;var burgerWrap=rightWrapper?rightWrapper.querySelector('.t446__burgerwrapper_withoutoverflow'):null;var rightWrapperWidth=t446_getPureWidth(rightWrapper);var rightMenuWrapWidth=rightMenuWrap?rightMenuWrap.offsetWidth:0;var additionalWrapWidth=additionalWrap?additionalWrap.offsetWidth:0;var additionalWrapFloating=additionalWrap?additionalWrap.style.float||window.getComputedStyle(additionalWrap).float:'';var blockHeight=menuheight>0?menuheight:80;if(window.innerWidth>980&&rightMenuWrapWidth+additionalWrapWidth>rightWrapperWidth){menu.style.height=blockHeight*2+'px';if(additionalWrap)additionalWrap.style.float='right';if(burgerWrapOverflow)burgerWrapOverflow.style.display='table-cell';if(burgerWrap)burgerWrap.style.display='none'}else{if(menu.offsetHeight>blockHeight)menu.style.height=blockHeight+'px';if(additionalWrap&&additionalWrapFloating==='right')additionalWrap.style.float='none';if(burgerWrapOverflow)burgerWrapOverflow.style.display='none';if(burgerWrap)burgerWrap.style.display='table-cell'}}
function t446_getPureWidth(el){if(!el)return 0;var elWidth=el.offsetWidth;var elPaddingLeft=parseInt(window.getComputedStyle(el).paddingLeft,10)||0;var elPaddingRight=parseInt(window.getComputedStyle(el).paddingRight,10)||0;var width=elWidth-(elPaddingLeft+elPaddingRight);return width>0?width:0}
function t446_createMobileMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;t_onFuncLoad('t_menu__createMobileMenu',function(){t_menu__createMobileMenu(recid,'.t446')});var linkItems=rec.querySelectorAll('.t-menu__link-item');var submenuClassList=['t978__menu-link_hook','t978__tm-link','t966__tm-link','t794__tm-link','t-menusub__target-link',];Array.prototype.forEach.call(linkItems,function(link){link.addEventListener('click',function(){var isSubmenuHook=submenuClassList.some(function(submenuClass){return link.classList.contains(submenuClass)});if(isSubmenuHook)return;t446_hideMenuOnMobile(link,rec)})});var wrappersLinks=rec.querySelectorAll('.t446__logowrapper2 a, .t446__right_buttons_wrap a');Array.prototype.forEach.call(wrappersLinks,function(link){link.addEventListener('click',function(){t446_hideMenuOnMobile(link,rec)})})}
function t446_hideMenuOnMobile(link,rec){if(!rec||!link||window.innerWidth>=980)return!1;var url=link.href?link.href.trim():'';var menu=rec.querySelector('.t446');var burger=rec.querySelector('.tmenu-mobile');if(url&&link.matches('[href*="#"]')){if(burger)burger.classList.remove('tmenu-mobile_opened');if(menu){if(menu.classList.contains('t446__positionabsolute')||(burger&&!burger.classList.contains('.tmenu-mobile_positionfixed'))){menu.style.display='none';menu.style.opacity='0'}else{t_onFuncLoad('t_menu__FadeOut',function(){t_menu__FadeOut(menu,300)})}}}}
function t450_showMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t450');var overlay=rec.querySelector('.t450__overlay');var menuElements=rec.querySelectorAll('.t450__overlay, .t450__close, a[href*="#"]');if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');document.body.classList.add('t450__body_menushowed');if(menu)menu.classList.add('t450__menu_show');if(overlay)overlay.classList.add('t450__menu_show');if(menu){menu.addEventListener('clickedAnchorInTooltipMenu',function(){t450_closeMenu(menu,overlay)})}
Array.prototype.forEach.call(menuElements,function(element){element.addEventListener('click',function(){if(element.closest('.tooltipstered, .t-menusub__target-link, .t794__tm-link, .t966__tm-link, .t978__tm-link'))
return;if(element.href&&(element.href.substring(0,7)==='#price:'||element.href.substring(0,9)==='#submenu:'))
return;t450_closeMenu(menu,overlay)})});document.addEventListener('keydown',function(e){if(e.keyCode===27){document.body.classList.remove('t390__body_popupshowed');var popups=document.querySelectorAll('.t390');Array.prototype.forEach.call(popups,function(popup){popup.classList.remove('t390__popup_show')})}});rec.addEventListener('click',function(e){if(e.target.closest('.t966__tm-link, .t978__tm-link, .t-menusub__target-link')){t450_checkSize(recid);if(e.target.closest('.t978__tm-link')){setTimeout(function(){var hookLink=e.target.closest('.t978__tm-link');var menuBlock=hookLink.nextElementSibling;var submenuLinks=menuBlock?menuBlock.querySelectorAll('.t978__menu-link'):[];Array.prototype.forEach.call(submenuLinks,function(link){link.addEventListener('click',function(){t450_checkSize(recid)})})},300)}}});menu.addEventListener('menuOverflow',function(){t450_checkSize(recid)});t450_highlight(recid)}
function t450_closeMenu(menu,overlay){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t450__body_menushowed');if(menu)menu.classList.remove('t450__menu_show');if(overlay)overlay.classList.remove('t450__menu_show')}
function t450_checkSize(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t450'):null;if(!menu)return;var container=menu.querySelector('.t450__container');var topContainer=menu.querySelector('.t450__top');var rightContainer=menu.querySelector('.t450__rightside');setTimeout(function(){var topContainerHeight=topContainer?topContainer.offsetHeight:0;var rightContainerHeight=rightContainer?rightContainer.offsetHeight:0;var containerPaddingTop=container?window.getComputedStyle(container).paddingTop:'0';var containerPaddingBottom=container?window.getComputedStyle(container).paddingBottom:'0';containerPaddingTop=parseInt(containerPaddingTop,10);containerPaddingBottom=parseInt(containerPaddingBottom,10);if(topContainerHeight+rightContainerHeight+containerPaddingTop+containerPaddingBottom>document.documentElement.clientHeight){menu.classList.add('t450__overflowed')}else{menu.classList.remove('t450__overflowed')}},300)}
function t450_appearMenu(recid){var rec=document.getElementById('rec'+recid);var burger=rec?rec.querySelector('.t450__menu__content'):null;if(!burger)return;var burgerAppearOffset=burger?burger.getAttribute('data-appearoffset'):'';var burgerHideOffset=burger?burger.getAttribute('data-hideoffset'):'';if(burgerAppearOffset){burgerAppearOffset=t450_appearMenuParseNumber(burgerAppearOffset);if(window.pageYOffset>=burgerAppearOffset){if(burger.classList.contains('t450__beforeready')){burger.classList.remove('t450__beforeready')}}else{burger.classList.add('t450__beforeready')}}
if(burgerHideOffset){burgerHideOffset=t450_appearMenuParseNumber(burgerHideOffset);var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);if(window.pageYOffset+window.innerHeight>=scrollHeight-burgerHideOffset){if(!burger.classList.contains('t450__beforeready')){burger.classList.add('t450__beforeready')}}else if(burgerAppearOffset){if(window.pageYOffset>=burgerAppearOffset){burger.classList.remove('t450__beforeready')}}else{burger.classList.remove('t450__beforeready')}}}
function t450_appearMenuParseNumber(string){if(string.indexOf('vh')>-1){string=Math.floor(window.innerHeight*(parseInt(string)/100))}
return parseInt(string,10)}
function t450_initMenu(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t450'):null;var overlay=rec?rec.querySelector('.t450__overlay'):null;var burger=rec?rec.querySelector('.t450__burger_container'):null;var menuLinks=rec?rec.querySelectorAll('.t-menu__link-item.t450__link-item_submenu'):[];var hook=menu?menu.getAttribute('data-tooltip-hook'):'';if(hook){document.addEventListener('click',function(e){if(e.target.closest('a[href="'+hook+'"]')){e.preventDefault();t450_closeMenu(menu,overlay);t450_showMenu(recid);t450_checkSize(recid)}})}
if(burger){burger.addEventListener('click',function(){t450_closeMenu(menu,overlay);t450_showMenu(recid);t450_checkSize(recid)})}
window.addEventListener('resize',function(){t450_checkSize(recid)});if(!window.isMobile)return;Array.prototype.forEach.call(menuLinks,function(link){link.addEventListener('click',function(){t450_checkSize(recid)})})}
function t450_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll(".t450__menu a[href='"+url+"'], "+".t450__menu a[href='"+url+"/'], "+".t450__menu a[href='"+pathname+"'], "+".t450__menu a[href='/"+pathname+"'], "+".t450__menu a[href='"+pathname+"/'], "+".t450__menu a[href='/"+pathname+"/']"+(hash?", .t450__menu a[href='"+hash+"']":''));var rec=document.getElementById('rec'+recid);var menuLinks=rec?rec.querySelectorAll('.t450__menu a'):[];Array.prototype.forEach.call(menuLinks,function(link){if(link.getAttribute('data-highlighted-by-user')!=='y')link.classList.remove('t-active')});Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t702_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;rec.setAttribute('data-animationappear','off');rec.setAttribute('data-popup-subscribe-inited','y');rec.style.opacity=1;var documentBody=document.body;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');var submitHref=rec.querySelector('.t-submit[href*="#"]');if(popupTooltipHook){t_onFuncLoad('t_popup__addAttributesForAccessibility',function(){t_popup__addAttributesForAccessibility(popupTooltipHook)});document.addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href$="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t702_showPopup(recId);t_onFuncLoad('t_popup__resizePopup',function(){t_popup__resizePopup(recId)});t702__lazyLoad();if(analitics&&window.Tilda){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}});t_onFuncLoad('t_popup__addClassOnTriggerButton',function(){t_popup__addClassOnTriggerButton(document,popupTooltipHook)})}
popup.addEventListener('scroll',t_throttle(function(){t702__lazyLoad()}));popup.addEventListener('click',function(event){var windowWithoutScrollBar=window.innerWidth-17;if(event.clientX>windowWithoutScrollBar)return;if(event.target===this)t702_closePopup(recId)});popupCloseBtn.addEventListener('click',function(){t702_closePopup(recId)});if(submitHref){submitHref.addEventListener('click',function(){if(documentBody.classList.contains('t-body_scroll-locked')){documentBody.classList.remove('t-body_scroll-locked')}})}
for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t702_closePopup(recId);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');documentBody.classList.add('t-body_popupshowed')},300)}}})}
function t702_escClosePopup(event){if(event.key==='Escape')t702_closePopup(recId)}
popup.addEventListener('tildamodal:show'+popupTooltipHook,function(){document.addEventListener('keydown',t702_escClosePopup)});popup.addEventListener('tildamodal:close'+popupTooltipHook,function(){document.removeEventListener('keydown',t702_escClosePopup)});rec.addEventListener('conditional-form-init',function(){t_onFuncLoad('t_form__conditionals_addFieldsListeners',function(){t_form__conditionals_addFieldsListeners(recId,function(){t_popup__resizePopup(recId)})})},{once:!0})}
function t702_lockScroll(){var documentBody=document.body;if(!documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=typeof window.pageYOffset!=='undefined'?window.pageYOffset:(document.documentElement||documentBody.parentNode||documentBody).scrollTop;documentBody.classList.add('t-body_scroll-locked');documentBody.style.top='-'+bodyScrollTop+'px';documentBody.setAttribute('data-popup-scrolltop',bodyScrollTop)}}
function t702_unlockScroll(){var documentBody=document.body;if(documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=documentBody.getAttribute('data-popup-scrolltop');documentBody.classList.remove('t-body_scroll-locked');documentBody.style.top=null;documentBody.removeAttribute('data-popup-scrolltop');document.documentElement.scrollTop=parseInt(bodyScrollTop)}}
function t702_showPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;var windowWidth=window.innerWidth;var screenMin=rec.getAttribute('data-screen-min');var screenMax=rec.getAttribute('data-screen-max');if(screenMin&&windowWidth<parseInt(screenMin,10))return;if(screenMax&&windowWidth>parseInt(screenMax,10))return;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var ranges=rec.querySelectorAll('.t-range');var documentBody=document.body;if(ranges.length){Array.prototype.forEach.call(ranges,function(range){t702__triggerEvent(range,'popupOpened')})}
t_onFuncLoad('t_popup__showPopup',function(){t_popup__showPopup(popup)});if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){setTimeout(function(){t702_lockScroll()},500)}
t702__lazyLoad();t702__triggerEvent(popup,'tildamodal:show'+popupTooltipHook);t_onFuncLoad('t_forms__calculateInputsWidth',function(){t_forms__calculateInputsWidth(recId)})}
function t702_closePopup(recId){var rec=document.getElementById('rec'+recId);var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var popupAll=document.querySelectorAll('.t-popup_show:not(.t-feed__post-popup):not(.t945__popup)');if(popupAll.length==1){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t-body_popupshowed')}else{var newPopup=[];for(var i=0;i<popupAll.length;i++){if(popupAll[i].getAttribute('data-tooltip-hook')===popupTooltipHook){popupAll[i].classList.remove('t-popup_show');newPopup.push(popupAll[i])}}
if(newPopup.length===popupAll.length){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t-body_popupshowed')}}
if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');popup.classList.remove('t-popup_show');document.body.classList.remove('t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){t702_unlockScroll()}
t_onFuncLoad('t_popup__addFocusOnTriggerButton',function(){t_popup__addFocusOnTriggerButton()});setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);t702__triggerEvent(popup,'tildamodal:close'+popupTooltipHook)}
function t702_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{hitType:'pageview',page:virtPage,title:virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t702_onSuccess(form){t_onFuncLoad('t_forms__onSuccess',function(){t_forms__onSuccess(form)})}
function t702__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t702__triggerEvent(el,eventName){var event;if(typeof window.CustomEvent==='function'){event=new CustomEvent(eventName)}else if(document.createEvent){event=document.createEvent('HTMLEvents');event.initEvent(eventName,!0,!1)}else if(document.createEventObject){event=document.createEventObject();event.eventType=eventName}
event.eventName=eventName;if(el.dispatchEvent){el.dispatchEvent(event)}else if(el.fireEvent){el.fireEvent('on'+event.eventType,event)}else if(el[eventName]){el[eventName]()}else if(el['on'+eventName]){el['on'+eventName]()}}
function t1014_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t1014');if(!container)return;rec.setAttribute('data-animationappear','off');rec.setAttribute('data-popup-subscribe-inited','y');rec.style.opacity=1;var documentBody=document.body;var hrefs=rec.querySelectorAll('a[href*="#"]');var popup=rec.querySelector('.t-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');if(popupTooltipHook){t_onFuncLoad('t_popup__addAttributesForAccessibility',function(){t_popup__addAttributesForAccessibility(popupTooltipHook)});document.addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t1014_createPopup(recId);t_onFuncLoad('t_popup__resizePopup',function(){t_popup__resizePopup(recId)});t1014__lazyLoad();if(analitics&&window.Tilda){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}});t_onFuncLoad('t_popup__addClassOnTriggerButton',function(){t_popup__addClassOnTriggerButton(document,popupTooltipHook)})}
popup.addEventListener('scroll',t_throttle(function(){t1014__lazyLoad()}));popup.addEventListener('click',function(event){if(event.target===this)t1014_closePopup()});popupCloseBtn.addEventListener('click',t1014_closePopup);for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||(url.substring(0,7)!='#price:'&&url.substring(0,7)!='#order:')){t1014_closePopup();if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');documentBody.classList.add('t-body_popupshowed')},300)}}})}}
function t1014_lockScroll(){var documentBody=document.body;if(!documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=typeof window.pageYOffset!=='undefined'?window.pageYOffset:(document.documentElement||documentBody.parentNode||documentBody).scrollTop;documentBody.classList.add('t-body_scroll-locked');documentBody.style.top='-'+bodyScrollTop+'px';documentBody.setAttribute('data-popup-scrolltop',bodyScrollTop)}}
function t1014_unlockScroll(){var documentBody=document.body;if(documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=documentBody.getAttribute('data-popup-scrolltop');documentBody.classList.remove('t-body_scroll-locked');documentBody.style.top=null;documentBody.removeAttribute('data-popup-scrolltop');document.documentElement.scrollTop=parseInt(bodyScrollTop)}}
function t1014_createPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t1014');if(!container)return;var popup=rec.querySelector('.t-popup');var documentBody=document.body;t_onFuncLoad('t_popup__showPopup',function(){t_popup__showPopup(popup)});if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t1014__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){setTimeout(function(){t1014_lockScroll()},500)}
document.addEventListener('keydown',t1014_escClosePopup)}
function t1014_escClosePopup(event){if(event.key==='Escape')t1014_closePopup()}
function t1014_closePopup(){var popupAll=document.querySelectorAll('.t-popup');if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t-body_popupshowed');document.body.classList.remove('t1014__body_popupshowed');for(var i=0;i<popupAll.length;i++){popupAll[i].classList.remove('t-popup_show')}
if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){t1014_unlockScroll()}
t_onFuncLoad('t_popup__addFocusOnTriggerButton',function(){t_popup__addFocusOnTriggerButton()});setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);document.removeEventListener('keydown',t1014_escClosePopup)}
function t1014__lazyLoad(){var allRecords=document.getElementById('allrecords');if(window.lazy==='y'||(allRecords&&allRecords.getAttribute('data-tilda-lazy')==='yes')){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t1014_onSuccess(form){t_onFuncLoad('t_forms__onSuccess',function(){t_forms__onSuccess(form)})}
function t905_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t905');if(!container)return;t905_unifyHeights(recId);window.addEventListener('resize',function(){t905_unifyHeights(recId)});window.addEventListener('load',function(){t905_unifyHeights(recId)});if(typeof jQuery!=='undefined'){$(container).on('displayChanged',function(){t905_unifyHeights(recId)})}else{container.addEventListener('displayChanged',function(){t905_unifyHeights(recId)})}}
function t905_unifyHeights(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t905');if(!container)return;var cards=rec.querySelectorAll('.t905__card');for(var i=0;i<cards.length;i++){var card=cards[i];var image=card.querySelector('.t905__image');var imageHeight=image.offsetHeight;var content=card.querySelector('.t905__content');var contentHeight=content.offsetHeight;if(contentHeight>imageHeight){image.style.height=contentHeight+'px';image.style.paddingBottom='initial'}}}
function t503_init(recId){t_onFuncLoad('t_card__moveClickOnCard',function(){t_card__moveClickOnCard(recId)});t_onFuncLoad('t_card__addFocusOnTab',function(){t_card__addFocusOnTab(recId)})}
function t1061_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var wrapperBlock=rec.querySelector('.t1061');var videoLazys=rec.querySelectorAll('.t-video-lazyload');if(videoLazys.length){t_onFuncLoad('t_video_lazyload__setHeight',function(){for(var i=0;i<videoLazys.length;i++){t_video_lazyload__setHeight(videoLazys[i])}
window.addEventListener('resize',function(){for(var i=0;i<videoLazys.length;i++){t_video_lazyload__setHeight(videoLazys[i])}});if(!wrapperBlock)return;wrapperBlock.addEventListener('displayChanged',function(){for(var i=0;i<videoLazys.length;i++){t_video_lazyload__setHeight(videoLazys[i])}})})}
var thumbnails=rec.querySelectorAll('.t1061__video-thumbnail');if(!thumbnails.length)return;Array.prototype.forEach.call(thumbnails,function(thumbnail){var videoWrap=thumbnail.closest('.t1061__wrap-video');var video=videoWrap.querySelector('.t-video-lazyload');var videoId=video.getAttribute('data-videolazy-id');var videoType=video.getAttribute('data-videolazy-type');t1061__setThumbnailImg(thumbnail,videoType,videoId);thumbnail.addEventListener('click',function(event){event.preventDefault();t_onFuncLoad('t_video_lazyload__addVideo',function(){t_video_lazyload__addVideo(video);thumbnail.remove()})})})}
function t1061__setThumbnailImg(thumbnailEl,videoType,videoId){function setBgImage(url){thumbnailEl.style.backgroundImage=url}
if(videoType==='youtube'){var standardDefinitionUrl='https://img.youtube.com/vi/'+videoId+'/sddefault.jpg';var fallbackUrl='https://img.youtube.com/vi/'+videoId+'/hqdefault.jpg';var tempImage=new Image();tempImage.onload=function(){if(this.width===120&&this.height===90){setBgImage('url("'+fallbackUrl+'")')}else{setBgImage('url("'+standardDefinitionUrl+'")')}};tempImage.onerror=function(){setBgImage('url("'+fallbackUrl+'")')};tempImage.src=standardDefinitionUrl;return}
if(videoType==='vimeo'){setBgImage('url("https://vumbnail.com/'+videoId+'.jpg")');return}
if(videoType==='kinescope'){setBgImage('url("https://kinescope.io/'+videoId+'/poster/md.jpg")');return}
if(videoType==='boomstream'){setBgImage('url("https://play.boomstream.com/'+videoId+'/poster")');return}
if(videoType==='rutube'){setBgImage('url("https://rutube.ru/api/video/'+videoId+'/thumbnail/?redirect=1")');return}}
function t890_init(recId,offset){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t890');if(!container)return;var windowOffset=offset||window.innerHeight;rec.setAttribute('data-animationappear','off');rec.style.opacity=1;window.addEventListener('scroll',t_throttle(function(){if(window.pageYOffset>windowOffset){container.style.display='block'}else{t890__fadeOut(container)}},200));var isSafari=/^((?!chrome|android).)*safari/i.test(navigator.userAgent);rec.addEventListener('click',function(e){if(e.target.closest('.t890__arrow')){isSafari?t890__animateScrollPolyfill(0):t890__scrollToTop()}})}
function t890__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},20)}
function t890__scrollToTop(){if(window.isIE){window.scrollTo(0,0)}else{window.scrollTo({left:0,top:0,behavior:'smooth',})}}
function t890__animateScrollPolyfill(target){var documentHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var bottomViewportPoint=documentHeight-document.documentElement.clientHeight;if(target>bottomViewportPoint)target=bottomViewportPoint;if(target===window.pageYOffset)return!1;var currentPosition=window.pageYOffset;var step=(target-currentPosition)/30;var difference=window.pageYOffset;var timerID=setInterval(function(){difference+=step;window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if((target-currentPosition<0&&window.pageYOffset<=target)||(target-currentPosition>0&&window.pageYOffset>=target)){clearInterval(timerID);document.body.removeAttribute('data-scrollable')}},10)}
function t875_init(){if(document.layers){document.captureEvents(Event.MOUSEDOWN)}
document.onmousedown=t875_click;document.oncontextmenu=function(event){event=event||window.event;var sender=event.target||event.srcElement;if(sender&&(sender.tagName.match(/INPUT|TEXTAREA/i)||sender.hasAttribute('contenteditable')||(sender.parentElement&&sender.parentElement.hasAttribute('contenteditable')))){return}else{return!1}};t875_preventSelection(document);t875_preventUserSelect()}
function t875_preventUserSelect(){var oldStyle=document.body.getAttribute('style');document.body.style.cssText=oldStyle+'-ms-user-select: none;'+'-moz-user-select: none;'+'-webkit-user-select: none;'+'user-select: none;'+'-webkit-touch-callout: none;'}
function t875_click(event){t875_returnPrevent(event);if(document.all){if(event.button===2){return!1}}
if(document.layers){if(event.which===3){return!1}}}
function t875_preventSelection(element){var preventSelection=!1;t875_addHandler(element,'mousemove',function(){if(preventSelection){t875_removeSelection()}});t875_addHandler(element,'mousedown',function(event){event=event||window.event;var sender=event.target||event.srcElement;preventSelection=sender&&!sender.tagName.match(/INPUT|TEXTAREA/i)&&!sender.hasAttribute('contenteditable')&&sender.parentElement&&!sender.parentElement.hasAttribute('contenteditable')});t875_addHandler(element,'mouseup',function(){if(preventSelection){t875_removeSelection()}
preventSelection=!1});t875_addHandler(element,'keydown',t875_killCtrlA);t875_addHandler(element,'keyup',t875_killCtrlA);t875_addHandler(element,'keydown',t875_killCtrlU);t875_addHandler(element,'keyup',t875_killCtrlU);t875_addHandler(element,'keydown',t875_killAltCmdI);t875_addHandler(element,'keyup',t875_killAltCmdI);t875_addHandler(element,'keydown',t875_killCtrlShiftI);t875_addHandler(element,'keyup',t875_killCtrlShiftI)}
function t875_addHandler(element,event,handler){if(element.attachEvent){element.attachEvent('on'+event,handler)}else if(element.addEventListener){element.addEventListener(event,handler,!1)}}
function t875_removeSelection(){if(window.getSelection){window.getSelection().removeAllRanges()}else if(document.selection&&document.selection.clear){document.selection.clear()}}
function t875_killCtrlU(event){t875_returnPrevent(event);var key=event.keyCode||event.which;if((event.ctrlKey&&key=='U'.charCodeAt(0))||(event.altKey&&event.metaKey&&(key=='U'.charCodeAt(0)||key=='u'.charCodeAt(0)))){if(event.preventDefault){event.preventDefault()}else{event.returnValue=!1}}}
function t875_killAltCmdI(event){t875_returnPrevent(event);var key=event.keyCode||event.which;if(event.altKey&&event.metaKey&&(key=='I'.charCodeAt(0)||key=='i'.charCodeAt(0))){if(event.preventDefault){event.preventDefault()}else{event.returnValue=!1}}}
function t875_killCtrlShiftI(event){t875_returnPrevent(event);var key=event.keyCode||event.which;if(event.shiftKey&&event.ctrlKey&&(key=='I'.charCodeAt(0)||key=='i'.charCodeAt(0))){if(event.preventDefault){event.preventDefault()}else{event.returnValue=!1}}}
function t875_killCtrlA(event){event=event||window.event;var sender=event.target||event.srcElement;if(sender&&(sender.tagName.match(/INPUT|TEXTAREA|BUTTON/i)||sender.hasAttribute('contenteditable')||(sender.parentElement&&sender.parentElement.hasAttribute('contenteditable')))){return}
var key=event.keyCode||event.which;if((event.ctrlKey&&key=='A'.charCodeAt(0))||(event.metaKey&&key=='A'.charCodeAt(0))){t875_removeSelection();if(event.preventDefault){event.preventDefault()}else{event.returnValue=!1}}}
function t875_returnPrevent(event){event=event||window.event;var sender=event.target||event.srcElement;if(sender&&(sender.tagName.match(/INPUT|TEXTAREA/i)||sender.hasAttribute('contenteditable')||(sender.parentElement&&sender.parentElement.hasAttribute('contenteditable')))){return}}
function t886_init(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var notificationBlock=rec.querySelector('.t886');var closeButton=rec.querySelector('.t886__btn');var storageItem=notificationBlock.getAttribute('data-storage-item');var lastOpen;try{lastOpen=localStorage.getItem(storageItem)}catch(error){console.log('Your web browser does not support localStorage. Error status: ',error)}
if(!lastOpen){notificationBlock.classList.remove('t886_closed')}
if(closeButton){closeButton.addEventListener('click',function(event){notificationBlock.classList.add('t886_closed');try{localStorage.setItem(storageItem,Math.floor(Date.now()/1000))}catch(error){console.log('Your web browser does not support localStorage. Error status: ',error)}
event.preventDefault()})}}